#!/bin/bash - 
#===============================================================================
#
#          FILE: back
# 
#         USAGE: ./back 
# 
#   DESCRIPTION: back to the backup file backuprecord_2014.c in ~/software 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Tang (Tang), tangchao90908@sina.com
#  ORGANIZATION: KLA
#       CREATED: 10/07/12 10:14:50 CST
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

date >> ~/software/backuprecord_2014.c
cat >> ~/software/backuprecord_2014.c
#echo '-----------------------------------------'
#tail -5 ~/software/backuprecord_2014.c
#echo '-----------------------------------------'
echo "//==============================" >> ~/software/backuprecord_2014.c
echo 'backup record ----100% done !!!'
#echo '-----------------------------------------'
