#!/bin/bash
# scriptname cpto
echo "--------------------------------------"
#echo "cp to ctang@202.121.49.52:~/..." for kla 
echo "cp to ctang@argo:~/ ... " for ictp
echo "--------------------------------------"
ls -A
echo "--------------------------------------"
read a
echo "--------------------------------------"
echo "OK,but where ?"
echo "--------------------------------------"
read b
echo "--------------------------------------"
#scp $a tangchao@202.121.49.52:~/$b
scp $a ctang@argo:~/$b
