#!/bin/bash - 
#===============================================================================
#
#          FILE: del
# 
#         USAGE: ./del 
# 
#   DESCRIPTION:  # use to ::delete the temp files!
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Tang (Tang), tangchao90908@sina.com
#  ORGANIZATION: KLA
#       CREATED: 10/07/12 10:05:13 CST
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

# scriptname delu
echo '-----------------------------------------'
rm *~
rm .*.swp
rm .*~
rm *.o
echo '-----------------------------------------'
echo '1000% done !!!'
echo '-----------------------------------------'
ls -A
