#!/bin/bash - 
#===============================================================================
#
#          FILE: del
# 
#         USAGE: ./del 
# 
#   DESCRIPTION:  # use to ::delete the all but one
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Tang (Tang), tangchao90908@sina.com
#  ORGANIZATION: KLA
#       CREATED: 10/07/12 10:05:13 CST
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

# scriptname delu
execption="000"
#=================================================== 
while getopts ":te:" opt; do
    case $opt in
        t) TEST=1 ;;
        e) execption=$OPTARG ;;
        \?) echo $USAGE && exit 1
    esac
done

shift $(($OPTIND - 1))
#=================================================== 
echo execption=$execption

color -n 1 7 " delete all the file, but "
color -n 7 1 " $execption "
color 1 7 "yes or no?"

read answer
if [ $answer = "yes" ];then


exit
ech '-----------------------------------------'
rm *~
rm .*.swp
rm .*~
rm *.o
echo '-----------------------------------------'
echo '1000% done !!!'
echo '-----------------------------------------'
ls -A
