#!/bin/bash - 
#===============================================================================
#
#          FILE: smm
# 
#         USAGE: ./smm 
# 
#   DESCRIPTION: to call sm & plot the $1 vs $2 
#                or just run the $1.sm
# 		  		& to run sm & ps2pdf & open this pdf
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Tang (Tang), tangchao90908@sina.com
#  ORGANIZATION: KLA
#       CREATED: 04/03/2013 13:10:45 CST
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

if [ $# -lt 1 ]; then
	echo "Useage: smm darafile line1 line2 OR smm xxx.sm"
	exit
fi
if [ $# -eq 2 ]; then
	echo "Useage: smm darafile line1 line2 OR smm xxx.sm"
	exit
fi

if [ $# -eq 1 ]; then
echo "--------------------------------------"
sm -m $1 
a=$(echo $1 | sed -e "s/.sm/.eps/g") 
# change .sm to .pdf and give this value to a
ps2pdf $a
b=$(echo $a  | sed -e "s/.eps/.pdf/g") 
# change .sm to .pdf and give this value to a
killall AdobeAcrobat
echo $b
open $b
#echo ${#1} # get length of $1
else
	head -15  ~/Shell/standard.sm | awk '{gsub(/standard90908/,"smm90908temp");gsub(/line1/,"'$2'");gsub(/line2/,"'$3'");gsub(/data89897/,"'$1'");print}' > smm90908temp.sm
	sm -m smm90908temp.sm
	ps2pdf smm90908temp.eps
	killall AdobeAcrobat
	echo smm90908temp.pdf
	open smm90908temp.pdf

	rm smm90908temp.sm smm90908temp.eps
fi
