#!/bin/bash - 
#===============================================================================
#
#          FILE: gradsbias
# 
#         USAGE: ./gradsbias 
# 
#   DESCRIPTION: to call grads & plot the $var in the $ifile
#       OPTIONS: --- $1: ifile; $2: var; $3: month
#  REQUIREMENTS: --- stdbiasmap.gs in ~/GrADS, GrADSNcPrepare
#          BUGS: --- sometimes you have to run GrADSNcPrepare 
#         NOTES: ---
#        AUTHOR: Tang (Tang), tangchao90908@sina.com
#  ORGANIZATION: KLA
#       CREATED: 04/03/2013 13:10:45 CST
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

if [ $# -lt 3 ]; then
	echo "Useage: gradsbias + variable + infile (*.ctl) + month (1~12)"

	exit
fi
var=$1
ifile=$2.ctl
month=$3

pathgs=~/GrADS/stdbiasmap.gs

#================= change directory
nn=$(echo $2 | awk -F '/' '{print NF}')
echo $nn
if [ $nn -lt 2 ]; then
	cd $(pwd)
else
	dir=$(echo $2 | awk -F '/' '{for(i=1;i<NF;i++) printf $i"/";printf "\n"}' )
	cd $dir
fi
#=================================================== 

GrADSNcPrepare $2

if [ $var = "pr" ]; then
	cat  $pathgs | awk '{gsub(/varName90908/,"'$var'");\
		gsub(/ifile90908/,"'$ifile'");gsub(/month90908/,"'$month'");\
		gsub(/title90908/,"precip RegCM-OBS (mm/day)");\
		gsub(/title89897/,"precip RegCM-OBS (%)");\
		gsub(/obs90908/,"precip.ymon.mean.nc");\
		gsub(/obsfactor90908/,"*1");\
		gsub(/obsvar90908/,"precip");\
		gsub(/factor90908/,"*86400");print}' > stdmap.temp.gs
else
	if [ $var = "tas" ]; then

		cat  $pathgs | awk '{gsub(/varName90908/,"'$var'");\
			gsub(/ifile90908/,"'$ifile'");gsub(/month90908/,"'$month'");\
			gsub(/title90908/,"T2m RegCM-OBS (Celsius degree)");\
			gsub(/obs90908/,"air.ymon.mean.nc");\
			gsub(/obsvar90908/,"air");\
			gsub(/obsfactor90908/,"-273.15");\
			gsub(/title89897/,"T2m RegCM-OBS (%)");\
			gsub(/factor90908/,"-273.15");print}' > stdmap.temp.gs
	else
		echo "Sorry, i cannot handle this variable now."
	fi
fi

#head -75 stdmap.temp.gs
#exit

echo $var $ifile $month
echo "--------------------------------------"
grads -lbc "run stdmap.temp.gs"
rm bias.$var.$month.gmf stdmap.temp.gs
#killall Preview
open bias.$var.$month.eps
echo "--------------------------------------"
echo output: bias.$var.$month.eps
exit
